metadata:
  git.branch: agl-branch
  image.type: AGL
  job.arch: arm64
  job.name: AGL-short-smoke-wip
  kernel.tree: AGL-kernel-tree
  kernel.version: AGL-kernel-version
  kernel.defconfig_base: defconfig
  kernel.defconfig: defconfig+CONFIG_AGL=y
  platform.mach: renesas
  platform.name: r8a7796-m3ulcb
  vcs.url: https://download.automotivelinux.org/AGL/release/dab/4.0.2/m3ulcb-nogfx/deploy/images/m3ulcb/

device_type: r8a7796-m3ulcb
job_name: AGL-short-smoke-wip

timeouts:
  job:
    minutes: 30
  action:
    minutes: 15
  connection:
    minutes: 5
priority: medium
visibility: public

protocols:
  lava-xnbd:
    port: auto

actions:
- deploy:
    timeout:
      minutes: 15
    to: nbd
    os: oe
    failure_retry: 2
    kernel:
      url: https://download.automotivelinux.org/AGL/release/dab/4.0.2/m3ulcb-nogfx/deploy/images/m3ulcb/Image
    initrd:
      url: https://download.automotivelinux.org/AGL/release/dab/4.0.2/m3ulcb-nogfx/deploy/images/m3ulcb/initramfs-netboot-image-m3ulcb.ext4.gz
      allow_modify: false
    nbdroot:
      url: https://download.automotivelinux.org/AGL/release/dab/4.0.2/m3ulcb-nogfx/deploy/images/m3ulcb/core-image-minimal-m3ulcb.ext4.xz
      compression: xz
    dtb:
      url: https://download.automotivelinux.org/AGL/release/dab/4.0.2/m3ulcb-nogfx/deploy/images/m3ulcb/Image-r8a7796-m3ulcb.dtb

- boot:
    timeout:
      minutes: 10
    method: u-boot
    prompts:
      - "root@m3ulcb:~"
      - '/ #'

    auto_login:
      login_prompt: "login:"
      username: root
    commands: nbd
    type: booti
    transfer_overlay:
      download_command: wget
      unpack_command: tar -C / -xvpf
- test:
    definitions:
    - repository: https://git.automotivelinux.org/src/qa-testdefinitions
      from: git
      path: test-suites/yocto-ptest.yaml
      name: yocto-ptest

- test:
    definitions:
    - repository: https://git.automotivelinux.org/src/qa-testdefinitions
      from: git
      path: test-suites/short-smoke/busybox.yaml
      name: busybox
    - repository: https://git.automotivelinux.org/src/qa-testdefinitions
      from: git
      path: test-suites/short-smoke/smoke-tests-basic.yaml
      name: smoke-tests-basic
    - repository: https://git.automotivelinux.org/src/qa-testdefinitions
      from: git
      path: test-suites/short-smoke/service-check.yaml
      name: service-check
- test:
    timeout:
      minutes: 2
    definitions:
    - repository:
        metadata:
          format: Lava-Test Test Definition 1.0
          name: inline-test
          description: "Inline test to validate test framewrok health"
          os:
          - debian
          scope:
          - functional
        run:
          steps:
          - lava-test-set start set-pass
          - lava-test-case always-pass --shell true
          - lava-test-set stop set-pass
          - lava-test-set start set-fail
          - lava-test-case always-fail --shell false
          - lava-test-set stop set-fail
      from: inline
      name: health-test
      path: inline/health-test.yaml
